version: '3' 
services: 
  server:
    build: . 
    ports:       
      - '8080:8080'
    environment:
      WAIT_HOSTS: mongo:27017
  mongo: #Adding Mongo into the docker-compose
    image: mongo:4.2.5
    ports:
      - '27017:27017'
